Styling fixes
codazen/react-relay-graphql-starter-kit pull request #10
Opened 2017-02-07 08:51 UTC by wesley-kiyohara

- Font in inputs were different from the rest of the page
- Add button was slightly misaligned with main input
- Changed cursor on add button to pointer, cursor when updating an existing to-do-item to be text

2017-02-07 16:19 UTC, munetake approved these changes

2017-02-07 17:11 UTC, mike-merchant requested changes

2017-02-07 17:11 UTC, michael-merchant commented on app/styles/styles.css
> +  font-family: 'Open Sans', sans-serif;
Any reason not to put font family on html {}?

2017-02-07 18:29 UTC, rachelsrabbit commented on app/styles/styles.css
> +  font-family: 'Open Sans', sans-serif;
normalize.css (@imported) specifies rules on form tags (button, input, optgroup, select, textarea). Those rules override any font family specified on the html tag. Maybe a more general way to set the font-family would be to set it on all the html and form tags.

2017-02-08 15:56 UTC, mike-merchant approved these changes

2017-02-08 18:19 UTC, merged