List item checked
codazen/react-relay-graphql-starter-kit pull request #18
Opened 2017-04-10 20:02 UTC by raffaelnagel

Related to issue Allow tasks to be marked as completed / uncompleted #16

2017-04-11 01:40 UTC, munetake requested changes

2017-04-11 01:40 UTC, munetake commented on app/components/ListItem.js
> +              <span className={this.state.isChecked ? 'item-checked' : null} onClick={this.props.updateItem ? this.openEditMode : null}>
Element properties can all go on their own line here.

2017-04-11 01:40 UTC, munetake commented on app/components/ListItem.js
> +    this.setState({
Should we still set the checkmark here? Even if an updateItem callback isn't passed?

2017-04-11 01:40 UTC, munetake commented on app/styles/styles.css
> +}
Add newline at eof

2017-04-11 01:40 UTC, munetake commented on app/components/ListItem.js
> +              <label
This can go on a single line

2017-04-11 01:40 UTC, munetake commented on app/styles/styles.css
> +.list-item-component label {
If you could attach a couple of screenshots highlighting the new ui changes that would be awesome!

2017-04-13 23:57 UTC, raffaelnagel commented
All requested changes were committed.

2017-04-14 00:00 UTC, merged